### ISSUE TITLE
Please support this version of Origin stub

### ISSUE THREAD

**Issue by DarkerSquirrel** [PotatoOfDoom/OriginStubDecrypter#4]
Edit: I modified unknown_always_1 (type u2le) in ooa_section.ksy and :
 - offsets look good now for ImageBase and SizeofImage
 - offsets don't look good for ImportDirectory,BaseRelocationTable and ImportAddressTable

Decryptor fails to work:

C:\games\OriginStubDecrypter>python decryptOriginStub.py game.exe
Traceback (most recent call last):
  File "C:\games\OriginStubDecrypter\decryptOriginStub.py", line 176, in <module>
    main()
  File "C:\games\OriginStubDecrypter\decryptOriginStub.py", line 152, in main
    ooa_info = parse_ooa_section(pe_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\games\OriginStubDecrypter\decryptOriginStub.py", line 44, in parse_ooa_section
    return OoaWrapper(section_data).OoaData
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\games\OriginStubDecrypter\OriginDecrypter\OoaWrapper.py", line 24, in __init__
    self.version = versions[ooaMini.version_id_sha1_hash]
                   ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: b'&\xa2F\x0fCHL&\x91H\xc7\xac \x8a]X \x12\xef='

-------
Please add support for this version of Origin stub.


[ooa.zip](https://github.com/PotatoOfDoom/OriginStubDecrypter/files/12174675/ooa.zip)

**Comment by mirh** [comment]
Does https://github.com/BigApex/rse-ooa-decrypt help?
